import type { TutorialScenario } from '../../types/fmc';

export const airbusPreflight: TutorialScenario = {
  name: 'A320 Preflight (ENGM → ENBR)',
  description: 'Complete Airbus A320 MCDU setup — INIT A/B, F-PLN, PERF TO, and FUEL PRED.',
  steps: [
    {
      id: 'a_init_a_intro',
      instruction: 'You are on the INIT A page. This is the A320 equivalent of the Boeing POS INIT + RTE page combined. Enter FROM/TO (origin/destination), cost index, cruise flight level, and alternate.',
      expectedAction: 'INIT_A',
      validate: () => true,
      page: 'INIT_A',
      highlightField: 'L1',
    },
    {
      id: 'a_from_to',
      instruction: 'Enter FROM/TO in the format ENGM/ENBR (Oslo to Bergen). Type ENGM/ENBR on the keypad and press LSK L1.',
      expectedAction: 'ENGM/ENBR',
      validate: (input: string) => input.toUpperCase().includes('ENGM'),
      page: 'INIT_A',
      highlightField: 'L1',
    },
    {
      id: 'a_cost_index',
      instruction: 'Cost Index balances fuel vs time. Airbus typically uses lower CI values (0-99 range vs Boeing\'s 0-999). Enter 30 and press LSK L3.',
      expectedAction: '30',
      validate: (input: string) => parseInt(input) > 0,
      page: 'INIT_A',
      highlightField: 'L3',
    },
    {
      id: 'a_crz_fl',
      instruction: 'Cruise Flight Level. Norwegian domestic routes typically cruise at FL350-370. Enter 350 and press LSK L5.',
      expectedAction: '350',
      validate: (input: string) => parseInt(input) >= 100,
      page: 'INIT_A',
      highlightField: 'L5',
    },
    {
      id: 'a_altn',
      instruction: 'Alternate airport — where you divert if you can\'t land at destination. Enter ENZV (Stavanger) and press LSK R1.',
      expectedAction: 'ENZV',
      validate: (input: string) => input.toUpperCase().length === 4,
      page: 'INIT_A',
      highlightField: 'R1',
    },
    {
      id: 'a_flt_nbr',
      instruction: 'Flight number (callsign). Enter NAX123 and press LSK R3.',
      expectedAction: 'NAX123',
      validate: (input: string) => input.toUpperCase().length >= 3,
      page: 'INIT_A',
      highlightField: 'R3',
    },
    {
      id: 'a_init_b',
      instruction: 'Press LSK R6 (marked with →) to go to INIT B page for weight and balance data.',
      expectedAction: 'init_b',
      validate: () => true,
      page: 'INIT_A',
      highlightField: 'R6',
    },
    {
      id: 'a_zfw',
      instruction: 'Zero Fuel Weight (aircraft + payload, no fuel). Type 58.0 (58,000 kg for a loaded A320) and press LSK L1.',
      expectedAction: '58',
      validate: (input: string) => parseFloat(input) > 30,
      page: 'INIT_B',
      highlightField: 'L1',
    },
    {
      id: 'a_block',
      instruction: 'Block fuel — total fuel loaded. For this short flight, enter 5.0 (5,000 kg) and press LSK L3.',
      expectedAction: '5',
      validate: (input: string) => parseFloat(input) > 1,
      page: 'INIT_B',
      highlightField: 'L3',
    },
    {
      id: 'a_cg',
      instruction: 'Center of Gravity from the load sheet. Enter 28.0 and press LSK L5. A320 typical CG is 25-35%.',
      expectedAction: '28',
      validate: (input: string) => parseFloat(input) > 10,
      page: 'INIT_B',
      highlightField: 'L5',
    },
    {
      id: 'a_fpln',
      instruction: 'Press F-PLN (top row, 2nd button) to view and edit the flight plan.',
      expectedAction: 'F_PLN',
      validate: () => true,
      page: 'F_PLN',
      highlightField: 'F_PLN',
    },
    {
      id: 'a_perf_to',
      instruction: 'Press PERF (top row, 3rd button) to enter takeoff performance data.',
      expectedAction: 'PERF_TAKEOFF',
      validate: () => true,
      page: 'PERF_TAKEOFF',
      highlightField: 'PERF_TAKEOFF',
    },
    {
      id: 'a_v1',
      instruction: 'V1 — decision speed. Based on weight and runway, approximately 140 knots. Enter 140 and press LSK L1.',
      expectedAction: '140',
      validate: (input: string) => parseInt(input) > 100,
      page: 'PERF_TAKEOFF',
      highlightField: 'L1',
    },
    {
      id: 'a_vr',
      instruction: 'VR — rotation speed. Enter 145 and press LSK L3.',
      expectedAction: '145',
      validate: (input: string) => parseInt(input) > 100,
      page: 'PERF_TAKEOFF',
      highlightField: 'L3',
    },
    {
      id: 'a_v2',
      instruction: 'V2 — takeoff safety speed. Enter 150 and press LSK L5.',
      expectedAction: '150',
      validate: (input: string) => parseInt(input) > 100,
      page: 'PERF_TAKEOFF',
      highlightField: 'L5',
    },
    {
      id: 'a_flex',
      instruction: 'FLEX takeoff temperature — Airbus uses assumed temperature method for reduced thrust. Enter 45 (45°C) and press LSK R3. Higher flex = more thrust reduction = longer engine life.',
      expectedAction: '45',
      validate: (input: string) => parseInt(input) > 0,
      page: 'PERF_TAKEOFF',
      highlightField: 'R3',
    },
    {
      id: 'a_fuel_pred',
      instruction: 'Press R6 (→) or FUEL PRED to check fuel predictions.',
      expectedAction: 'perf_appr',
      validate: () => true,
      page: 'PERF_TAKEOFF',
      highlightField: 'R6',
    },
    {
      id: 'a_exec',
      instruction: 'Press EXEC (glowing green) to activate all entries. The Airbus MCDU now has a complete preflight setup.',
      expectedAction: 'EXEC',
      validate: () => true,
      page: 'FUEL_PRED',
      highlightField: 'EXEC',
    },
  ],
  setup: () => [],
};

export const airbusTutorialScenarios: TutorialScenario[] = [
  airbusPreflight,
];
