import type { FMCState } from '../types/fmc';

export function createBaseState(overrides: Partial<FMCState> = {}): FMCState {
  return {
    aircraft: 'BOEING_737',
    currentPage: 'IDENT',
    pageHistory: [],
    scratchpad: '',
    scratchpadError: null,
    demoMode: false,
    ident: { aircraftType: '737-800', engRating: '26K', navDataVersion: 'FMC21A1', opProgram: '2247662-03' },
    position: { refAirport: '', gate: '' },
    performance: { crzAlt: 0, costIndex: 0, zfw: 0, fuel: 0, cg: 0, reserve: 0 },
    takeoff: { runway: '', toMode: 'TO', assumedTemp: 0, v1: 0, vr: 0, v2: 0, trim: 0, oat: 0, windDir: 0, windSpeed: 0, qnh: 0 },
    landing: { runway: '', flaps: '', vref: 0, ilsFrequency: '', course: 0 },
    route: { origin: '', destination: '', flightNumber: '', companyRoute: '', routeString: '' },
    flightPlan: { origin: '', destination: '', flightNumber: '', route: '', waypoints: [] },
    pendingRoute: null,
    pendingFlightPlan: null,
    isModified: false,
    execLit: false,
    msgLight: false,
    mode: 'STANDBY',
    connectionStatus: 'DISCONNECTED',
    connectionMode: 'STANDALONE',
    legsPageIndex: 0,
    legsPageCount: 1,
    depArrSubPage: 'DEP',
    rteSubPage: 0,
    takeoffRefPageIndex: 0,
    hold: { fix: '', inboundCourse: 0, legTime: 1.0, legDist: 0, direction: 'R' },
    holdPending: null,
    fix: { refFix: '', radial: 0, distance: 0 },
    fixEntries: [
      { refFix: '', radial: 0, distance: 0 },
      { refFix: '', radial: 0, distance: 0 },
    ],
    deleteMode: false,
    editWaypointIndex: null,
    aircraftState: null,
    connectedAircraft: null,
    connectedAircraftType: null,
    connectedCapabilities: [],
    lastError: null,
    simVariables: {},
    failureMessage: null,
    externalDisplayData: null,
    efisL: {
      mode: 'MAP',
      range: 40,
      centered: false,
      side: 'L',
      overlays: {
        wpt: false,
        arpt: false,
        sta: false,
        data: false,
        pos: false,
        terr: false,
        wxr: false,
        tfc: false,
        cstr: false,
      },
    },
    efisR: {
      mode: 'MAP',
      range: 40,
      centered: false,
      side: 'R',
      overlays: {
        wpt: false,
        arpt: false,
        sta: false,
        data: false,
        pos: false,
        terr: false,
        wxr: false,
        tfc: false,
        cstr: false,
      },
    },
    brightness: 100,
    latency: 0,
    sessionStartTime: null,
    radios: {
      vor1: '113.90',
      vor2: '115.70',
      adf1: '342',
    },
    tutorialActive: false,
    tutorialCompleted: false,
    tutorialStepIndex: 0,
    tutorialScenario: null,
    tutorialStartTime: null,
    tutorialErrors: 0,
    tutorialHint: null,
    tutorialSkipAvailable: false,
    tutorialHighlight: null,
    tutorialConfidence: null,
    ...overrides,
  };
}
